<a href="https://colab.research.google.com/github/tchillusu/class-stuff/blob/main/TEDA_1040_Mod_3_Numpy_Classroom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
numbers_list = [5,9,15,25,40]
numbers_list

[5, 9, 15, 25, 40]

In [3]:
np.array(numbers_list)

array([ 5,  9, 15, 25, 40])

In [4]:
numbers_array = np.array(numbers_list)
numbers_array #array is a lot faster way to compute mathematical problems - Can't multiply a list without a for loop

array([ 5,  9, 15, 25, 40])

In [9]:
print(numbers_array / 3)
numbers_array * 3

[ 1.66666667  3.          5.          8.33333333 13.33333333]


array([ 15,  27,  45,  75, 120])

In [12]:
new_list = []
for x in numbers_list:
    y=x/3
    new_list.append(y)


new_list

[1.6666666666666667, 3.0, 5.0, 8.333333333333334, 13.333333333333334]

In [13]:
numbers_array.reshape(-1,1)


array([[ 5],
       [ 9],
       [15],
       [25],
       [40]])

In [24]:
np.linspace(0,20,20)  #find exact numbers between 0 and 20 including 0 and 20

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [25]:
np.arange(0, 20, 2) # from 0 to 20 in increments of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.random.random() # random number between 0 and 1

0.865026736285872

In [35]:
np.random.seed(123) #setting the seed will determine the same number every time as long as you use the same seed #
np.random.random()

0.6964691855978616

In [37]:
np.random.random() *10 # times it by 10 will give a random number between 1 and 10

2.268514535642031

In [38]:
print(numbers_array)
numbers_array.argmin() #will tell where in the array the smallest number is - its at index 0

[ 5  9 15 25 40]


0

In [39]:
numbers_array[0] # since we learned the position of the smallest number we can now pull that specific number

5

In [41]:
numbers_array.argmax() # will tell where in the array the largest number is - its at index 4

4

In [43]:
np.where(numbers_array > 12, 'big' , 'small') # if number is bigger than 12, true = big, false = small

array(['small', 'small', 'big', 'big', 'big'], dtype='<U5')

In [45]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [50]:
np.where(df['Age'] > 50, 'old', 'young')


array(['young', 'young', 'young', 'young', 'young', 'young', 'old',
       'young', 'young', 'young', 'young', 'old', 'young', 'young',
       'young', 'old', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'old', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'old', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'young', 'young', 'young', 'young',
       'young', 'young', 'young', 'old', 'young', 'old', 'young', 'young',
       'young', 'young', 

In [62]:
df['agetype'] = np.where(df['Age'] > 50, 'old', 'young')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked agetype    agetype2  
0      0         A/5 21171   7.2500   NaN        S   young       young  
1      0          PC 17599  71.2833   C85        C   young  middle age  
2      0  STON/O2. 3101282   7.9250   NaN        S   young  middle age  
3      0            113803  53.1000  C123        S   young  middle age  
4      0            373450   8.0500   NaN        S   young  middle age

In [63]:
df['agetype2'] = np.where(df['Age'] > 50, 'old', np.where(df['Age'] > 25, 'middle age', 'young'))
df.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked agetype    agetype2  
0      0         A/5 21171   7.2500   NaN        S   young       young  
1      0          PC 17599  71.2833   C85        C   young  middle age  
2      0  STON/O2. 3101282   7.9250   NaN        S   young  middle age  
3      0            113803  53.1000  C123        S   young  middle age  
4      0            373450   8.0500   NaN        S   young  middle age